---
- name: Prepare
  hosts: all
  gather_facts: true
  vars:
    elasticsearch_molecule_platform_packages:
      debian13:
        - procps
  tasks:
    - name: Install platform-specific packages (Debian)
      ansible.builtin.apt:
        name: "{{ elasticsearch_molecule_platform_packages[inventory_hostname] }}"
        state: present
        update_cache: true
      async: 600
      poll: 10
      when:
        - inventory_hostname in elasticsearch_molecule_platform_packages
        - ansible_facts["os_family"] == "Debian"

    - name: Install platform-specific packages (RedHat)
      ansible.builtin.dnf:
        name: "{{ elasticsearch_molecule_platform_packages[inventory_hostname] }}"
        state: present
      async: 600
      poll: 10
      when:
        - inventory_hostname in elasticsearch_molecule_platform_packages
        - ansible_facts["os_family"] == "RedHat"
