---
namespace: zupersero

name: elastic

version: 1.0.0

readme: README.md

authors:
- zupersero

description: An ansible collection for working and interacting with software in the elastic ecosystem

license:
- GNU General Public License v3.0

license_file: LICENSE

tags:
  - elastic
  - elk
  - kibana
  - fleet
  - security

dependencies: {}

repository: https://github.com/ZuperSero/zupersero.elastic

documentation: https://galaxy.ansible.com/ui/repo/published/zupersero/elastic

homepage: https://github.com/ZuperSero/zupersero.elastic

issues: https://github.com/ZuperSero/zupersero.elastic/issues

build_ignore: []
