---
elasticsearch_major_version: "{{ elasticsearch_version.split('.')[0] | default('9') }}"
elasticsearch_path_conf: "/etc/elasticsearch"

# Base JVM options (internal, always included)
_elasticsearch_jvm_base_options: |
  -Xms{{ elasticsearch_jvm_heap_size }}
  -Xmx{{ elasticsearch_jvm_heap_size }}
