---
- name: Converge
  hosts: molecule
  gather_facts: true
  tasks:
    - name: Converge flag
      ansible.builtin.debug:
        msg: |
          ***************************************
          ***************************************
          ********* Converge Started ************
          ***************************************
          ***************************************

    - name: Apply elasticsearch role
      ansible.builtin.include_role:
        name: zupersero.elastic.elasticsearch
