---
- name: Converge
  hosts: molecule
  gather_facts: true
  tasks:
    - name: Converge flag
      ansible.builtin.debug:
        msg: |
          ***************************************
          ***************************************
          ********* Converge Started ************
          ***************************************
          ***************************************

    - name: Apply elasticsearch role with bootstrap
      ansible.builtin.include_role:
        name: zupersero.elastic.elasticsearch
      vars:
        elasticsearch_bootstrap: true
      tags:
        - molecule-idempotence-notest

    - name: Apply elasticsearch role without bootstrap
      ansible.builtin.include_role:
        name: zupersero.elastic.elasticsearch
      vars:
        elasticsearch_bootstrap: false
